# VMCS main config
# IP, ports, motd, RCON, JMX, Net Compression

server_ip: 0.0.0.0
server_port: 26000
motd: V server instance
# JMX monitoring -
jmx_monitoring: false
network_compression: 256

# Online mode, whitelist, max_players

# mojang - Online mode, velocity - Velocity, offline - LAN mode
server_mode: offline
velocity_secret: ""
# Whitelist (based on nicknames) -
whitelist: false
max_players: 25

# Other

brand_name: "VMS"
#spawn-protection=0
#view-distance=10
#simulation-distance=10
#broadcast-console-to-ops=true
#broadcast-rcon-to-ops=true
#motd=Create Adventure
#network-compression-threshold=256